Imports MySql.Data.MySqlClient


Public Class Collection
    Private SQL As New sqlcontrol
    Private authuser As String
    Private Sub txtcontrol_TextChanged(sender As Object, e As EventArgs) Handles txtcontrol.TextChanged

    End Sub

    Private Sub BtnSearchRecord_Click(sender As Object, e As EventArgs) Handles BtnSearchRecord.Click
        ColGrid.Rows.Clear()


        Dim stracctexist As String
        SQL.AddParam("@assess", "V")
        SQL.AddParam("@colstat", "P")
        '  SQL.AddParam("@userid", loginuserid)
        SQL.AddParam("@control", txtcontrol.Text)
        SQL.ExecQuery("Select * from rpt_record_hdr a  inner join rpt_application b on a.TDN_no = b.TDN_no where a.TDN_no = @control")

        For Each r As DataRow In SQL.DBDT.Rows
            stracctexist = (r("TDN_no").ToString)
            lblid.Text = r("TDN_no").ToString


            ColGrid.Rows.Add(r("TDN_no"), r("Owner_Name"), r("Total_amt"), r("Email_add"), r("Owner_Address"), r("Location"))
        Next
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Me.Close()
        MainMenu.btnrptcol.Enabled = True
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs)
        'email sender
        Dim aa As String

        aa = "https://mail.google.com/mail/?view=cm&fs=1&to=" & ColGrid.CurrentRow.Cells(3).Value.ToString & " &su=Health Certificate Receipt" & "&tf=1&body=Hello, Good day!%0d%0aAttached here is your Official Receipt.  %0d%0aThank you and Keep Safe!%0d%0a%0d%0a%0d%0aThis email is autogenerated, please do not reply."

        System.Diagnostics.Process.Start(aa)
    End Sub

    Private Sub ColGrid_CellContentClick(sender As Object, e As DataGridViewCellEventArgs) Handles ColGrid.CellContentClick

        If e.RowIndex = -1 Then
            Exit Sub

        End If

        If e.ColumnIndex = 6 Then
            Dim aa As String

            aa = "https://mail.google.com/mail/?view=cm&fs=1&to=" & ColGrid.CurrentRow.Cells(3).Value.ToString & " &su=Health Certificate Receipt" & "&tf=1&body=Hello, Good day!%0d%0aAttached here is your Official Receipt.  %0d%0aThank you and Keep Safe!%0d%0a%0d%0a%0d%0aThis email is autogenerated, please do not reply."

            System.Diagnostics.Process.Start(aa)
        End If
    End Sub

    Private Sub PanelAppoinment_Paint(sender As Object, e As PaintEventArgs) Handles PanelAppoinment.Paint

    End Sub
    Public Sub LoadAdmingrid()


        Dim btneval As New DataGridViewButtonColumn
        ColGrid.Columns.Add(btneval)
        With btneval
            .HeaderText = "ACTION"
            .Width = 130
            .Name = "btneval"
            .Text = "SEND RECEIPT"
            .UseColumnTextForButtonValue = True


        End With
    End Sub

    Private Sub Collection_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        LoadAdmingrid()
    End Sub
End Class