Imports MySql.Data.MySqlClient

Public Class Collector
    Private SQL As New sqlcontrol2
    Private authuser As String

    Private loginuserid As Integer = LogIn.lblid.Text
    Dim mRow As Integer = 0
    Dim newpage As Boolean = True
    Private Sub txt_name_TextChanged(sender As Object, e As EventArgs)

    End Sub

    Private Sub txtacct1_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtacct1.KeyPress
        txtacct2.Focus()

    End Sub

    Private Sub txtacct1_TextChanged(sender As Object, e As EventArgs) Handles txtacct1.TextChanged

    End Sub

    Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
        Me.Close()
        MainMenu.btnbusinesscol.Enabled = True

    End Sub

    Private Sub Collector_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ' txtacct1.Focus()
        txtacct1.Select()
        ' loaddata()
        LoadAdmingrid()
    End Sub

    Private Sub BtnSearchRecord_Click(sender As Object, e As EventArgs) Handles BtnSearchRecord.Click
        searchrec()


    End Sub

    Public Sub loaddata()
        SQL.AddParam("@assess", "V")
        SQL.AddParam("@colstat", "P")
        '  SQL.AddParam("@userid", loginuserid)

        SQL.ExecQuery("Select a.recordid, b.applicationid , a.accountno, b_name , b.gross_dec, a.b_line, c.assess_status, c.payment_status from business_record_hdr a inner join business_application_tbl b on a.recordID = b.recordID inner join business_applicationstatus_dtl c on b.applicationID = c.applicationID where c.assess_status = 'V' and c.payment_status = 'P' ")

        For Each r As DataRow In SQL.DBDT.Rows
            ColGrid.Rows.Add(r("recordid"), r("applicationid"), r("accountno"), r("b_name"), r("gross_dec"), r("b_line"), r("payment_status"))
        Next
    End Sub


    Public Sub LoadAdmingrid()


        Dim btneval As New DataGridViewButtonColumn
        ColGrid.Columns.Add(btneval)
        With btneval
            .HeaderText = "ACTION"
            .Width = 130
            .Name = "btneval"
            .Text = "CONFIRM PAYMENT"
            .UseColumnTextForButtonValue = True


        End With
    End Sub

    Private Sub txtacct2_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtacct2.KeyPress
        If e.KeyChar = ChrW(Keys.Enter) Then
            searchrec()

        End If
    End Sub

    
    Private Sub txtacct2_TextChanged(sender As Object, e As EventArgs) Handles txtacct2.TextChanged

    End Sub

    Private Sub ColGrid_CellContentClick(sender As Object, e As DataGridViewCellEventArgs) Handles ColGrid.CellContentClick

        If e.RowIndex = -1 Then
            Exit Sub

        End If

        If e.ColumnIndex = 12 Then
            'comment an para email
            'Dim aa As String

            'aa = "https://mail.google.com/mail/?view=cm&fs=1&to=" & ColGrid.CurrentRow.Cells(5).Value.ToString & " &su=Health Certificate Receipt" & "&tf=1&body=Hello, Good day!%0d%0aAttached here is your Official Receipt.  %0d%0aThank you and Keep Safe!%0d%0a%0d%0a%0d%0aThis email is autogenerated, please do not reply."

            'System.Diagnostics.Process.Start(aa)






            'Dim strbusinessid As String
            'Dim stracct As String = ColGrid.CurrentRow.Cells(2).Value
            'SQL.AddParam("@acct", stracct)
            'SQL.ExecQuery("Select * from ONLINE.business_record_hdr where accountno = @acct")
            'For Each r As DataRow In SQL.DBDT.Rows
            '    strbusinessid = (r("businessid").ToString)
            'Next

            Dim intappid As Integer = ColGrid.CurrentRow.Cells(1).Value

            'SQL.AddParam("@bid", strbusinessid)
            'SQL.AddParam("@appid", intappid)
            'SQL.AddParam("@acct", stracct)
            'SQL.AddParam("@dt", dt_Appoinment.Value)
            'SQL.ExecQuery("Insert into ONLINE.business_permit_status (applicationID, AccountNo , Status, BusinessID, DatePending) values (@appid , @acct ,'P', @bid , @dt )")
            '' MessageBox.Show("Set to Paid")
            'ColGrid.Rows.Clear()

            Dim strdatenow As String = DateTime.Now

            SQL.AddParam("@appid", intappid)
            SQL.AddParam("@pdate", strdatenow)

            SQL.ExecQuery("update ONLINE.business_applicationstatus_dtl set IsPaid = '1', paid_dttime = @pdate where applicationID = @appid")

            MessageBox.Show("Payment Confirmed")
        End If
    End Sub

    Private Sub Panel5_Paint(sender As Object, e As PaintEventArgs) Handles Panel5.Paint

    End Sub

    Private Sub Label1_Click(sender As Object, e As EventArgs) Handles Label1.Click

    End Sub

    Public Sub searchrec()
        ColGrid.Rows.Clear()

        Dim straccount As String = txtacct1.Text + "-" + txtacct2.Text


        Dim stracctexist As String
        SQL.AddParam("@assess", "V")
        SQL.AddParam("@colstat", "P")
        '  SQL.AddParam("@userid", loginuserid)
        SQL.AddParam("@account", straccount)
        SQL.ExecQuery("Select a.recordid, b.applicationid , a.accountno, b_name , fire_local_amount, amountToPay, a.b_line, c.assess_status, c.payment_status, fullname,owneraddress,birthdate, email_add,cedula_amt from ONLINE.business_record_hdr a inner join ONLINE.business_application_tbl b on a.recordID = b.recordID inner join ONLINE.business_applicationstatus_dtl c on b.applicationID = c.applicationID inner join ONLINE.business_assessment_dtl d on b.applicationid = d.ApplicationID where c.assess_status = 'V'  and a.accountno = @account ")

        For Each r As DataRow In SQL.DBDT.Rows
            stracctexist = (r("accountno").ToString)



            ColGrid.Rows.Add(r("recordid"), r("applicationid"), r("accountno"), r("b_name"), r("amountToPay"), r("fire_local_amount"), r("cedula_amt"), r("email_add"), r("payment_status"), r("fullname"), r("owneraddress"), r("Birthdate"))
        Next

        If stracctexist = Nothing Then

            MessageBox.Show("This account has no assessment for this year", "Not Found", MessageBoxButtons.OK, MessageBoxIcon.Error)
        End If
    End Sub

End Class