
Imports MySql.Data.MySqlClient
Public Class HealthCardsend
    Private SQL As New sqlcontrol
    Private authuser As String
    Private Sub Button2_Click(sender As Object, e As EventArgs)

        'email sender
        Dim aa As String

        aa = "https://mail.google.com/mail/?view=cm&fs=1&to=" & ColGrid.CurrentRow.Cells(3).Value.ToString & " &su=Health Certificate Receipt" & "&tf=1&body=Hello, Good day!%0d%0aAttached here is your Official Receipt.  %0d%0aThank you and Keep Safe!%0d%0a%0d%0a%0d%0aThis email is autogenerated, please do not reply."

        System.Diagnostics.Process.Start(aa)
    End Sub

    Private Sub Button5_Click(sender As Object, e As EventArgs) Handles Button5.Click
        Me.Close()
        MainMenu.btnhcsend.Enabled = True

    End Sub

    Private Sub BtnSearchRecord_Click(sender As Object, e As EventArgs) Handles BtnSearchRecord.Click
        ColGrid.Rows.Clear()




        Dim stracctexist As String
        SQL.AddParam("@assess", "V")
        SQL.AddParam("@colstat", "P")
        '  SQL.AddParam("@userid", loginuserid)
        SQL.AddParam("@control", txtcontrol.Text)
        SQL.ExecQuery("Select * from cho_online_payment where ApplicationID = @control")

        For Each r As DataRow In SQL.DBDT.Rows
            stracctexist = (r("ApplicationID").ToString)
            lblid.Text = r("ApplicationID").ToString


            ColGrid.Rows.Add(r("ApplicationId"), r("Lastname") + "," + r("FirstName") + " " + r("MiddleName"), r("Amount"), r("Email"), r("TypeOfApplication"), r("ClassificationID"), r("FeeFields"))
        Next
    End Sub

    Private Sub PanelAppoinment_Paint(sender As Object, e As PaintEventArgs) Handles PanelAppoinment.Paint

    End Sub

    Private Sub HealthCardsend_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        LoadAdmingrid()
    End Sub

    Private Sub ColGrid_CellContentClick(sender As Object, e As DataGridViewCellEventArgs) Handles ColGrid.CellContentClick
        If e.RowIndex = -1 Then
            Exit Sub

        End If

        If e.ColumnIndex = 7 Then
            Dim aa As String

            aa = "https://mail.google.com/mail/?view=cm&fs=1&to=" & ColGrid.CurrentRow.Cells(3).Value.ToString & " &su=Health Certificate Receipt" & "&tf=1&body=Hello, Good day!%0d%0aAttached here is your Official Receipt.  %0d%0aThank you and Keep Safe!%0d%0a%0d%0a%0d%0aThis email is autogenerated, please do not reply."

            System.Diagnostics.Process.Start(aa)
        End If
    End Sub
    Public Sub LoadAdmingrid()


        Dim btneval As New DataGridViewButtonColumn
        ColGrid.Columns.Add(btneval)
        With btneval
            .HeaderText = "ACTION"
            .Width = 130
            .Name = "btneval"
            .Text = "SEND RECEIPT"
            .UseColumnTextForButtonValue = True


        End With
    End Sub
End Class